# Generated by Django 2.2 on 2020-02-04 14:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(default='images/default_avatar.png', upload_to='images', verbose_name='avatar'),
        ),
    ]
