# Generated by Django 3.0.2 on 2020-02-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='media/default_avatar.png', upload_to=''),
        ),
    ]
