# Generated by Django 3.0.2 on 2020-01-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(default='new to mediap', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='occupy',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
