# Generated by Django 3.0.2 on 2020-02-04 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_account_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_account_followings_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
