# Generated by Django 3.0.2 on 2020-02-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200204_1403'),
        ('account', '0002_auto_20200204_1406'),
    ]

    operations = [
    ]
