# Generated by Django 2.2 on 2020-01-29 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200129_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_account_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
