# Generated by Django 2.1.5 on 2020-01-29 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200128_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(related_name='_account_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
