# Generated by Django 3.0.2 on 2020-01-26 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('parentId', models.IntegerField(null=True)),
                ('userId', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('picture', models.FileField(upload_to='images')),
                ('time', models.DateField(auto_now_add=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('voteDown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voteUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteUp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('textContent', models.TextField()),
                ('creatorPicture', models.FileField(upload_to='images')),
                ('adminId', models.IntegerField()),
                ('authorId', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('creatorName', models.CharField(max_length=50)),
                ('pictureContent', models.FileField(upload_to='images')),
                ('commentNumbers', models.IntegerField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Comment')),
                ('voteDown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteDown', to=settings.AUTH_USER_MODEL)),
                ('voteUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
