# Generated by Django 2.2 on 2020-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
