# Generated by Django 2.2 on 2020-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pictureContent',
            field=models.ImageField(default='images/default_avatar.png', upload_to='../images'),
        ),
    ]
