# Generated by Django 3.0.2 on 2020-01-29 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0002_auto_20200128_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='adminId',
        ),
        migrations.RemoveField(
            model_name='card',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='card',
            name='creatorName',
        ),
        migrations.RemoveField(
            model_name='card',
            name='creatorPicture',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='card',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='card_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_authour', to=settings.AUTH_USER_MODEL),
        ),
    ]
