# Generated by Django 3.0.2 on 2020-01-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200126_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.Comment'),
        ),
    ]
