# Generated by Django 2.2 on 2020-01-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200129_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='picture',
        ),
    ]
