# Generated by Django 2.1.5 on 2020-01-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_remove_comment_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pictureContent',
        ),
    ]
