# Generated by Django 3.0.2 on 2020-01-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200126_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='commentNumbers',
        ),
    ]
