# Generated by Django 2.2 on 2020-02-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200204_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='picture',
            new_name='pictureContent',
        ),
    ]
