# Generated by Django 3.0.2 on 2020-01-26 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0004_remove_card_commentnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='voteDown',
            field=models.ManyToManyField(null=True, related_name='voteDown', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='voteUp',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='voteDown',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='voteUp',
            field=models.ManyToManyField(null=True, related_name='voteUp', to=settings.AUTH_USER_MODEL),
        ),
    ]
