# Generated by Django 2.2 on 2020-02-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20200204_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default_avatar.ong', upload_to='images/')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Card')),
            ],
        ),
    ]
