# Generated by Django 2.1.5 on 2020-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_remove_card_picturecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='pictureContent',
            field=models.FileField(default='images/AI_HW1.png', upload_to='images'),
        ),
    ]
