# Generated by Django 3.0.2 on 2020-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20200204_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pictureContent',
            field=models.ImageField(default='images/default_avatar.png', upload_to='images', verbose_name='pictureContent'),
        ),
    ]
