# Generated by Django 3.0.2 on 2020-02-04 15:46

import Post.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200204_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pictureContent',
            field=versatileimagefield.fields.VersatileImageField(default='images/default_avatar.png', upload_to=Post.models.upload, verbose_name='pictureContent'),
        ),
    ]
