# Generated by Django 2.2 on 2020-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_card_picturecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pictureContent',
            field=models.ImageField(default='images/AI_HW1.png', upload_to='images'),
        ),
    ]
