# Generated by Django 2.2 on 2020-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pictureContent',
            field=models.ImageField(default='images/default_avatar.png', upload_to='images', verbose_name='pictureContent'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/default_avatar.ong', upload_to='images'),
        ),
    ]
