# Generated by Django 3.0.2 on 2020-01-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20200130_1520'),
        ('Post', '0005_card_picturecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_channel', to='channel.Channel'),
        ),
    ]
