# Generated by Django 3.0.2 on 2020-01-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200126_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='children',
        ),
    ]
