# Generated by Django 2.2 on 2020-02-04 16:27

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200204_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pictureContent',
            field=versatileimagefield.fields.VersatileImageField(default='images/default_avatar.png', upload_to='images', verbose_name='pictureContent'),
        ),
    ]
