# Generated by Django 3.0.2 on 2020-01-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20200130_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_seen',
            field=models.IntegerField(default=0),
        ),
    ]
