# Generated by Django 3.0.2 on 2020-01-27 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_remove_comment_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_Modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
