# Generated by Django 3.0.2 on 2020-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_userprofile_avatar'),
        ('Post', '0008_card_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='voteDown',
            field=models.ManyToManyField(blank=True, related_name='voteDown', to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='card',
            name='voteUp',
            field=models.ManyToManyField(blank=True, to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='voteDown',
            field=models.ManyToManyField(blank=True, to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='voteUp',
            field=models.ManyToManyField(blank=True, related_name='voteUp', to='UserProfile.UserProfile'),
        ),
    ]
