# Generated by Django 3.0.2 on 2020-01-31 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_comment_is_seen'),
        ('Post', '0006_auto_20200130_2024'),
    ]

    operations = [
    ]
