# Generated by Django 2.2 on 2020-01-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_merge_20200131_0911'),
        ('Post', '0009_merge_20200131_1004'),
    ]

    operations = [
    ]
