# Generated by Django 2.1.3 on 2020-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('occupy', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=50)),
            ],
        ),
    ]
