# Generated by Django 3.0.2 on 2020-01-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=''),
        ),
    ]
