# Generated by Django 3.0.2 on 2020-01-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
