# Generated by Django 3.0.2 on 2020-02-05 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='media/default_avatar.png', upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('rules', models.CharField(max_length=50)),
                ('accounts', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(related_name='authours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
