# Generated by Django 3.0.2 on 2020-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_userprofile_avatar'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='authours',
            field=models.ManyToManyField(to='UserProfile.UserProfile'),
        ),
    ]
