# Generated by Django 2.2 on 2020-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20200129_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(default='images/AI_HW1.png', upload_to=None),
        ),
    ]
