# Generated by Django 3.0.2 on 2020-01-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_userprofile_avatar'),
        ('channel', '0002_auto_20200127_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='authours',
            field=models.ManyToManyField(related_name='authours', to='UserProfile.UserProfile'),
        ),
    ]
