# Generated by Django 3.0.2 on 2020-01-30 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0002_auto_20200129_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
