# Generated by Django 2.2 on 2020-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20200130_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(default='images/AI_HW1.png', upload_to='images'),
        ),
    ]
