# Generated by Django 3.0.2 on 2020-01-30 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0003_auto_20200130_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='followers',
        ),
        migrations.AddField(
            model_name='channel',
            name='accounts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
