# Generated by Django 3.0.2 on 2020-01-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20200130_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='authours',
            new_name='followers',
        ),
    ]
