# Generated by Django 2.2 on 2020-01-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20200130_1520'),
        ('channel', '0004_auto_20200130_2024'),
    ]

    operations = [
    ]
