# Generated by Django 2.2 on 2020-01-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_merge_20200131_1004'),
        ('channel', '0008_merge_20200131_0911'),
    ]

    operations = [
    ]
